baseURL = "https://hyoromo.github.io/apps/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-theme-learn"
googleAnalytics = 'G-HDQZZ3YLN1'

defaultContentLanguage = "en"
metaDataFormat = "yaml"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  # Author of the site, will be used in meta information
  author = "hyoromo"
  # Description of the site, will be used in meta information
  description = "Sound game training app"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]

[Languages]
[Languages.en]
title = "Apps"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> Donation"
url = "https://www.amazon.jp/hz/wishlist/ls/370CVCOUAFLVK?ref_=wl_share"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> Privacy Policy"
url = "https://hyoromo.github.io/apps/privacy-policy/"
weight = 13


[Languages.jp]
title = "Apps"
weight = 2
languageName = "日本語"

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 寄付"
url = "https://www.amazon.jp/hz/wishlist/ls/370CVCOUAFLVK?ref_=wl_share"
weight = 12

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> プライバシーポリシー"
url = "https://hyoromo.github.io/apps/jp/privacy-policy/"
weight = 13


[Languages.zh]
title = "Apps"
weight = 3
languageName = "简体中文"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 捐赠"
url = "https://www.amazon.jp/hz/wishlist/ls/370CVCOUAFLVK?ref_=wl_share"
weight = 12

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 隐私政策"
url = "https://hyoromo.github.io/apps/zh/privacy-policy/"
weight = 13


[Languages.zh-TW]
title = "Apps"
weight = 4
languageName = "繁體中文"

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 捐贈"
url = "https://www.amazon.jp/hz/wishlist/ls/370CVCOUAFLVK?ref_=wl_share"
weight = 12

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 隱私政策"
url = "https://hyoromo.github.io/apps/zh-tw/privacy-policy/"
weight = 13


[Languages.ko]
title = "Apps"
weight = 2
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 기부"
url = "https://www.amazon.jp/hz/wishlist/ls/370CVCOUAFLVK?ref_=wl_share"
weight = 12

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 개인 정보 보호 정책"
url = "https://hyoromo.github.io/apps/ko/privacy-policy/"
weight = 13